version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: Username
      WORDPRESS_DB_PASSWORD: MyPassword
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./web/html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: Username
      MYSQL_PASSWORD: MyPassword
      MYSQL_ROOT_PASSWORD: RootPassword

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8210:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
   db_data:
   wordpress_data:
   phpmyadmin_data:
